### ISSUE TITLE
Documentation: French Readme translation

### ISSUE THREAD

**Issue by AlexLunaP** [alvarohghg/GymQuest#4]
### Summary

Write a translation of the project's Readme file in French.

### Basic Example

You can use tools like [StackEdit ](https://stackedit.io/) to preview the Readme file.

### Drawbacks

Expand the boundaries of the project.

**Comment by HugoLAMOUREUX** [comment]
Hi, could I get this issue assigned to me ? Also I should create another file like README_fr and put the translated version in it right ?

**Comment by AlexLunaP** [comment]
Sure! Yes, you can create another file for the translation. Thanks!
